repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Security: Scans for plain-text secrets/keys before committing
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: 'venv/|static/'

  # Security: Runs Bandit SAST scanner on your backend files
  - repo: https://github.com/pycqa/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-r", "-lll"]
        exclude: ^venv/

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
     - id: black

 # - repo: https://github.com/astral-sh/ruff
  #  rev: v0.15.18
   ##  - id: ruff
     #   args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
       - id: mypy
         args: [--ignore-missing-imports]
