"""Add MpesaTransaction table

Revision ID: 61e2f3f2fca3
Revises:
Create Date: 2026-06-10 05:56:01.023294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e2f3f2fca3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_checkout_request_id'), 'transactions', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_key'], ['licenses.license_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id')
    )
    op.drop_table('update_manifest')
    op.alter_column('devices', 'license_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('devices', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_constraint(op.f('unique_device_id'), 'devices', type_='unique')
    op.alter_column('licenses', 'assigned_users',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.create_unique_constraint(None, 'licenses', ['license_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licenses', type_='unique')
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.alter_column('licenses', 'assigned_users',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_unique_constraint(op.f('unique_device_id'), 'devices', ['device_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.alter_column('devices', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('devices', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('devices', 'license_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('update_manifest',
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latest_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sha256', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('mandatory', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('min_required_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('latest_version', name=op.f('updates_pkey')),
    comment='Poptest auto-updater db'
    )
    op.drop_table('mpesa_transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_checkout_request_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
